main/board/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<int:pk>', PostDetailView.as_view(), name='post'),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from board.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('post/', include('board.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/board/models.py
import os
import re
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings



class Category(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=255, unique=True, verbose_name='Название')
    content = models.TextField(max_length=1000, verbose_name='Текст')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')
    is_active = models.BooleanField(verbose_name="Статус", default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'post/{self.pk}'

    @property
    def images(self):
        return Image.objects.filter(post__pk=self.pk)

    @property
    def videos(self):
        return Video.objects.filter(post__pk=self.pk)

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-pk']


class Image(models.Model):
    alt = models.CharField(max_length=255, verbose_name='Описание изображения')
    url = models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='URL')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Объявление')

    def __str__(self):
        return self.alt

    @property
    def path(self):
        return os.path.join(settings.MEDIA_URL, str(self.url))

    class Meta:
        verbose_name = 'Изобржение'
        verbose_name_plural = 'Изобржения'
        ordering = ['-pk']


class Video(models.Model):
    url = models.URLField(verbose_name='Ссылка на Youtube',
                          help_text='Например: https://www.youtube.com/watch?v=jNQXAC9IVRw')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Видео')

    def __str__(self):
        return self.url

    @property
    def code(self):
        re_code = r'youtube.com\/watch\?v=([-a-zA-Z0-9]+)'
        code = re.findall(re_code, str(self.url))
        if code:
            return code[0]
        else:
            return ''

    class Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Объявление')
    content = models.TextField(max_length=500, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_accept = models.BooleanField(verbose_name="Подтвержден", default=False)
    is_active = models.BooleanField(verbose_name="Статус", default=True)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

main/board/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView,  DeleteView
from django.db.models import Count
from .models import Post, Category


class HomeView(ListView):
    model = Post
    template_name = 'board/home.html'
    context_object_name = 'posts'
    ordering = ['-created_at']

    def get_queryset(self):
        return super().get_queryset()[:4]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects \
            .annotate(number_post=Count('post')) \
            .filter(number_post__gt=0) \
            .order_by('-number_post')[:4]
        context['popular_posts'] = Post.objects.all() \
            .annotate(number_message=Count('message')) \
            .filter(number_message__gt=0) \
            .order_by('-number_message')[:4]
        context['popular_users'] = User.objects.all() \
            .annotate(number_post=Count('post')) \
            .filter(number_post__gt=0) \
            .order_by('-number_post')[:4]
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'board/post.html'
    context_object_name = 'post'

main/board/templates/board/home.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block top-section %}
<section class="hero-section">
    <div class="hero-slider owl-carousel">
        <div class="hero-item set-bg" data-setbg="/media/theme/img/slider/1.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 offset-lg-1">
                        <h2>Enter the Battle</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
                        <a href="#" class="site-btn">Read More</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero-item set-bg" data-setbg="/media/theme/img/slider/2.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 offset-lg-1">
                        <h2>Enter the Battle</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
                        <a href="#" class="site-btn">Read More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock top-section %}

{% block content %}

		<div class="container">
			<div class="row">
				<div class="col-lg-8 blog-posts">
					<div class="blog-post featured-post">
						<img src="/media/theme/img/blog/1.jpg" alt="">
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui. </p>
					</div>
					<div class="row">
						{% for post in posts %}
						<div class="col-md-6">
							<div class="blog-post">
								{% if post.images.0 %}
								<img src="{{ post.images.0.path }}" alt="{{ post.images.0.alt }}">
								{% else %}
								<img src="/media/theme/img/blog/5.jpg" alt="">
								{% endif %}
								<div class="post-date">{{ post.created_at|date:'d M, Y' }}</div>
								<h4>{{ post.title }}</h4>
								<div class="post-metas">
									<div class="post-meta">{{ post.user.username }}</div>
									<div class="post-meta"><a href="#">{{ post.category.name }}</a></div>
									<div class="post-meta">{{ post.message_set.count|is_plural:"отклик,отклика,откликов" }}</div>
								</div>
								<p>{{ post.content|truncatechars:150 }}</p>
								<a href="{{ post.get_absolute_url }}" class="read-more">Читать</a>
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
				<div class="col-lg-4 sidebar">
					<div class="sb-widget">
						<form class="sb-search">
							<input type="text" placeholder="Search">
						</form>
					</div>
					<div class="sb-widget">
						<h2 class="sb-title">Категории</h2>
						<ul class="sb-cata-list">
							{% for category in categories %}
							<li><a href="">{{ category.name }}<span>{{ category.post_set.count }}</span></a></li>
							{% endfor %}
						</ul>
					</div>
					<div class="sb-widget">
						<h2 class="sb-title">Популярные объявления</h2>
						<div class="latest-news-widget">
							{% for post in popular_posts %}
							<div class="ln-item">
								{% if post.images.0 %}
								<img src="{{ post.images.0.path }}" alt="{{ post.images.0.alt }}">
								{% else %}
								<img src="/media/theme/img/blog/5.jpg" alt="">
								{% endif %}
								<div class="ln-text">
									<div class="ln-date">{{ post.created_at|date:'d M, Y' }}</div>
									<h6>{{ post.title }}</h6>
									<div class="ln-metas">
										<div class="ln-meta">{{ post.user.username }}</div>
										<div class="ln-meta"><a href="{{ post.get_absolute_url }}">{{ post.category.name }}</a></div>
										<div class="ln-meta">{{ post.message_set.count|is_plural:"отклик,отклика,откликов" }}</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
					<div class="sb-widget">
						<a href="#" class="add">
							<img src="/media/theme/img/add-2.jpg" alt="">
						</a>
					</div>
					<div class="sb-widget">
						<h2 class="sb-title">Самые активные авторы</h2>
						<div class="latest-comments-widget">
							{% for user in popular_users %}
							<div class="lc-item">
								<img src="/media/theme/img/author-thumbs/1.jpg" alt="">
								<div class="lc-text">
									<h6>{{ user.username }}</h6>
									<div class="lc-date">{{ user.post_set.count|is_plural:"объявление,объявления,объявлений" }}</div>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock content %}

main/board/templates/board/post.html
{% extends 'base.html' %}
{% load custom_filters %}


{% block content %}
    <div class="row">

            <div class="blog-post single-post">
                <h3>{{ post.title }}</h3>
                <div class="post-metas">
                    <div class="post-meta">{{ post.user.username }}</div>
                    <div class="post-meta"><a href="#">{{ post.category.name }}</a></div>
                    <div class="post-meta">{{ post.message_set.count|is_plural:"отклик,отклика,откликов" }}</div>
                </div>
                <div class="post-date">{{ post.created_at|date:'d M, Y' }}</div>
                <p>{{ post.content }}</p>
                <div class="popup-gallery">
                    {% for image in post.images %}
                    <a href="{{ image.path }}" title="{{ image.alt}} " class="position-relative">
                        <img src="{{ image.path }}" >
                        <svg width="40px" height="40px" viewBox="0 0 16 16" class="bi bi-image" fill="#10ddb4" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M14.002 2h-12a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1zm-12-1a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2h-12z"/>
                          <path d="M10.648 7.646a.5.5 0 0 1 .577-.093L15.002 9.5V14h-14v-2l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71z"/>
                          <path fill-rule="evenodd" d="M4.502 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                        </svg>
                    </a>
                    {% endfor %}
                </div>
                <div class="popup-video">
                    {% for video in post.videos %}
                    <a class="popup-youtube position-relative" href="{{ video.url }}">
                        <img src="{% if video.code %}https://img.youtube.com/vi/{{ video.code }}/3.jpg {% else %} /media/theme/img/youtube.jpg {% endif %}" >
                        <svg width="40px" height="40px" viewBox="0 0 16 16" class="bi bi-film" fill="#10ddb4" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0h8v6H4V1zm8 8H4v6h8V9zM1 1h2v2H1V1zm2 3H1v2h2V4zM1 7h2v2H1V7zm2 3H1v2h2v-2zm-2 3h2v2H1v-2zM15 1h-2v2h2V1zm-2 3h2v2h-2V4zm2 3h-2v2h2V7zm-2 3h2v2h-2v-2zm2 3h-2v2h2v-2z"/>
                        </svg>
                    </a>
                    {% endfor %}
                </div>
            </div>

    </div>

{% endblock content %}

main/templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
<head>
	<title>!!!!!!!! - {% block head_title %}{% endblock head_title %}</title>
	<meta charset="UTF-8">
	<meta name="description" content="TheQuest Gaming Magazine Template">
	<meta name="keywords" content="gaming, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Favicon -->
	<link href="/media/theme/img/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
<!--	<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">-->
	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static '/css/magnific-popup.css' %}"/>
	<link rel="stylesheet" href="{% static '/css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static '/css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static '/css/slicknav.min.css' %}"/>
	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static '/css/style.css' %}"/>

    {% block style %}
    {% endblock style %}
  </head>

<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<a href="{% url 'home' %}" class="site-logo">
			<img src="/media/theme/img/logo.png" alt="logo">
		</a>
		<ul class="main-menu">
			<li><a href="{% url 'home' %}">Главная</a></li>
			<li><a href="characters.html">Объявления</a></li>
			<li><a href="game.html">Категории</a></li>
			{% if request.user.is_authenticated %}
			<li><a href="{% url 'account_logout' %}" class="text-success">Аккаунт</a></li>
			{% else %}
			<li><a href="{% url 'account_signup' %}" class="text-warning">Регистрация</a></li>
			<li><a href="{% url 'account_login' %}" class="text-success">Вход</a></li>
			{% endif %}
		</ul>
	</header>
	{% block body %}

	{% block top-section %}
    {% endblock top-section %}

	<section class="blog-section spad">
		<div class="container mt-5">
		{% block content %}
		{% endblock content %}
		</div>
	</section>

	{% block extra_body %}
	{% endblock extra_body %}

	{% endblock body %}
	<!-- Footer section -->
	<div class="footer-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3">
					<div class="footer-widget">
						<div class="about-widget">
							<img src="/media/theme/img/logo.png" alt="">
							<p>Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo. Morbi id dictum quam, ut commodo.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-2 col-sm-6">
					<div class="footer-widget">
						<h2 class="fw-title">Usfull Links</h2>
						<ul>
							<li><a href="">Games</a></li>
							<li><a href="">testimonials</a></li>
							<li><a href="">Reviews</a></li>
							<li><a href="">Characters</a></li>
							<li><a href="">Latest news</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-sm-6">
					<div class="footer-widget">
						<h2 class="fw-title">Services</h2>
						<ul>
							<li><a href="">About us</a></li>
							<li><a href="">Services</a></li>
							<li><a href="">Become a writer</a></li>
							<li><a href="">Jobs</a></li>
							<li><a href="">FAQ</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-sm-6">
					<div class="footer-widget">
						<h2 class="fw-title">Careeres</h2>
						<ul>
							<li><a href="">Donate</a></li>
							<li><a href="">Services</a></li>
							<li><a href="">Subscriptions</a></li>
							<li><a href="">Careers</a></li>
							<li><a href="">Our team</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget fw-latest-post">
						<h2 class="fw-title">Usfull Links</h2>
						<div class="latest-news-widget">
							<div class="ln-item">
								<div class="ln-text">
									<div class="ln-date">April 1, 2019</div>
									<h6>10 Amazing new games</h6>
									<div class="ln-metas">
										<div class="ln-meta">By Admin</div>
										<div class="ln-meta">in <a href="#">Games</a></div>
										<div class="ln-meta">3 Comments</div>
									</div>
								</div>
							</div>
							<div class="ln-item">
								<div class="ln-text">
									<div class="ln-date">April 1, 2019</div>
									<h6>10 Amazing new games</h6>
									<div class="ln-metas">
										<div class="ln-meta">By Admin</div>
										<div class="ln-meta">in <a href="#">Games</a></div>
										<div class="ln-meta">3 Comments</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright"><a href=""><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></div>
		</div>
		<div class="social-links-warp">
			<div class="container">
				<div class="social-links">
					<a href="#"><i class="fa fa-instagram"></i><span>instagram</span></a>
					<a href="#"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
					<a href="#"><i class="fa fa-facebook"></i><span>facebook</span></a>
					<a href="#"><i class="fa fa-twitter"></i><span>twitter</span></a>
					<a href="#"><i class="fa fa-youtube"></i><span>youtube</span></a>
					<a href="#"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer section end -->

	<!--====== Javascripts & Jquery ======-->
	<script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static '/js/bootstrap.min.js' %}"></script>
	<script src="{% static '/js/jquery.slicknav.js' %}"></script>
	<script src="{% static '/js/owl.carousel.min.js' %}"></script>
	<script src="{% static '/js/circle-progress.min.js' %}"></script>
	<script src="{% static '/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static '/js/main.js' %}"></script>

	</body>
</html>